# Generated by Django 6.0.5 on 2026-05-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
