# Generated by Django 6.0.5 on 2026-05-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('closed', 'Closed'), ('note', 'Note Added'), ('replied', 'Reply Sent')], max_length=20),
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.TextField()),
                ('cc_email', models.TextField(blank=True, default='')),
                ('bcc_email', models.TextField(blank=True, default='')),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('signature', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.staff')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketReplyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_reply_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='myapp.ticketreply')),
            ],
        ),
    ]
