# Generated by Django 6.0.5 on 2026-05-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('Inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
