# Generated by Django 6.0.5 on 2026-05-14 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_staff_signature_alter_tickethistory_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='myapp.ticketnote'),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='myapp.ticketreply'),
        ),
    ]
