# Generated by Django 6.0.5 on 2026-05-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
