# Generated by Django 6.0.5 on 2026-05-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_staff_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('to_email', models.TextField()),
                ('cc_email', models.TextField(blank=True, null=True)),
                ('bcc_email', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
