# Generated by Django 6.0.5 on 2026-05-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ticket_bcc_email_ticket_cc_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='bcc_email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='cc_email',
        ),
    ]
