# Generated by Django 6.0.5 on 2026-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_ticket_bcc_email_remove_ticket_cc_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bcc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
