# Generated by Django 6.0.5 on 2026-05-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_emailattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
