# Generated by Django 6.0.5 on 2026-05-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_sentemail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='sender_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
